### PR TITLE
Polymer2

### PR DESCRIPTION
**Pull request by mdgbayly**
@dbatiste @dlockhart @omsmith 

Hi Gents

Been reading more on Polymer 2 and got all excited that it's going to make our Activity Feed app much faster so I decided to start on the path of upgrading some of the BrightspaceUI stuff to hybrid so that I can then start upgrading our app. 

I started with some of the base components (d2l-demo-template-ui, d2l-colors, d2l-typography) and have PRs in the works for them. 

But then I figured it would be cool to find out just how much faster things are going to be, so I took a look at making polyperf work with Polymer 2, because I figured that would help with understanding the performance improvements for hybrid/legacy/class based elements as we upgrade things.

Unfortunately the results are not quite what I was hoping for and Polymer 2 if anything seems slower than Polymer 1.  Maybe you guys could take a look and see if you think there is something wrong in my approach or maybe there is something in the way that polyperf works that is causing Polymer 2 to not perform so well. The first line of the table shows the results from running polyperf prior to my PR changes

| Version | input | test1-element | test2-element |
| ------------- | ------------- | ------------- | ------------- |
| Pre-PR (1.9.1)  | 12ms | 512ms | 1496ms | 
| Polymer 1 (1.4) (sample)  | 11ms | 486ms | 1409ms | 
| Polymer 2 legacy (sample)  | 10ms | 557ms | 1619ms | 
| Polymer 2 class (sample2)  | 11ms | 536ms | 1584ms | 

_The reason the Polymer 1 tests are using 1.4 is because I fixed to that version in the 1.x variants thinking that was what I had for the Pre-PR tests, but realized after that the Pre-PR stuff was actually using 1.9.1_

### CODE REVIEW

**Comment by dlockhart** [comment]
I'm not sure if I'm surprised by these results or not. I think I would expect the hybrid mode in Polymer 1.x to be slower -- it's still relying on the v0 custom elements (which only exist in Chrome) and probably has a bunch of extra code such that it can work with both Polymer 1 and 2.

I would however expect non-hybrid pure Polymer 2 mode to be faster but maybe the elements under test are so simple that there just aren't enough opportunities for optimization?

One other big source of optimization could be from the ne polyfill loader, which does feature detection and only loads/executes the polyfills that are actually needed. You may want to try that:
https://www.polymer-project.org/2.0/docs/polyfills

**Comment by mdgbayly** [comment]
Yeh - maybe given that Chrome has native implementations for v0 and v1, the switch from Polymer 1 to Polymer 2 is not so significant in Chrome where I ran those tests.

I should try running these before/after tests on some other browsers too to see if there is a performance boost for browsers that do rely on the Polyfills.

**Comment by dlockhart** [comment]
I would look especially hard at Safari, which has native support for shadow DOM v1 and custom elements v1. Also double-check that native shadow DOM is enabled in the Polymer init settings.

**Comment by dbatiste** [comment]
Hey Martin, I am curious if you use the `strategy="onedev"` and the `delay`?  I think I typically did with most of my tests since I felt that std dev yielded more relevant results.  Also, if you notice times creeping up with subsequent runs, I recommend using the `delay` attribute.  I observed this in certain instances where the browser was not able to keep up with clean-up tasks from one run to the next.   Something to watch out for.

**Comment by mdgbayly** [comment]
legacy

**Pull request closed without merging**
